# Private inputs
token_amount = "100889171966"
user_address = "148801026924260256610193814272670429076"
account_data = [96,145,127,56,205,185,82,221,14,57,8,2,114,50,18,68,31,154,222,214,201,47,180,239,168,110,202,115,58,50,22,126,111,242,9,12,193,177,41,163,84,254,165,130,187,51,239,148,148,106,103,195,96,68,103,50,159,145,159,168,194,90,247,69,254,151,118,125,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# Public inputs
token_mint = "128361351006304707967660486577446064708"
state_root = "19728612341612261001590879027664809175833880053785335563002564599175700954426"
min_required = "1000000000"