# Private inputs
amount = "1000000000"
secret = "4123720789808858505883247010843728666538496942582127819719252313268239846135"
nullifier = "2763404511324125220446322872335542185867402908262727714048181120636822066266"
merkle_path = ["15492360485435104441452163938514871604424058051864221973267940242406891291625","19764185461263626802922524600405607940537337757963622883205557817180576505237","0","0","20719109675870613135775629761488024798164462904408412825933627151183952191004","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]
merkle_indices = [1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# Public inputs
root = "10459857762451694354125210557482241227899887284009491674425608899537130617209"
nullifier_hash = "14218189790163698874070386407762755088570392139406785455106458994302000648225"
amount_pub = "1000000000"
recipient = "277417465905138607916961171296110012153"
mint = "129282128564130995696722549098627213520"
pool_id = "154699630455504375900067812619897785572"