# Private inputs
amount = "1000000000"
secret = "16554448674358622286756690873871160732253250108119245274627377136803642638056"
nullifier = "4617171890290744493979199083474347043534026571988610555181977437461428792468"
merkle_path = ["12995921353813252182925299030030590855341884027134334460394272331303812664246","0","0","0","3265921088247697898171388414761768175039924446210790375637395214759041692513","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]
merkle_indices = [1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# Public inputs
root = "2166785774237552413394497177196357014752829291158362863254429026688238190513"
nullifier_hash = "13839858929553309975482544235520646958841925304341978966054196005439295833187"
amount_pub = "1000000000"
recipient = "60395113643289275478785703175362067794"
mint = "128361351006304707967660486577446064708"
pool_id = "85925391845841954356583641049633581258"