# Private inputs
amount = "1000000000"
secret = "8148736117425487962666402145173327256976349465071622167365973170203283154932"
nullifier = "19680517639959601395248730109017229295011434226154126029389191798439913507838"
merkle_path = ["0","0","4828659381412588019225858899969517090399079810276343404546940028345353134870","6980811404976838001442300912868308690900881868710943784397764224346298305677","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]
merkle_indices = [0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# Public inputs
root = "14356418347495495645287375239125068735051928765003169425132396776963283990794"
nullifier_hash = "5151265180386985832014029998524799498596011323560970458884143652139096289946"
amount_pub = "1000000000"
recipient = "277417465905138607916961171296110012153"
mint = "129282128564130995696722549098627213520"
pool_id = "154699630455504375900067812619897785572"